"""
google_client.py
================
Queries the Gemini API (gemini-2.0-flash) with Google Search grounding enabled.

Why Gemini instead of Google Custom Search API
-----------------------------------------------
Google's AI Overviews are generated by Gemini and are not accessible via any
public API.  The closest legitimate proxy is to query Gemini directly with
Google Search grounding turned on — this forces Gemini to search the web
in real time before answering, so its responses reflect current content
exactly as a user would experience in Google AI Mode.

Google Search grounding is included in Gemini's free tier (1,500 req/day).
Our usage is ~8 req/day, well within that limit.

API key
-------
Stored in the GEMINI_API_KEY environment variable / GitHub Secret.
Get a free key at: https://aistudio.google.com/app/apikey
"""

import os
import logging

logger = logging.getLogger(__name__)

_MODEL = "gemini-2.0-flash"

_SYSTEM_PROMPT = (
    "You are a knowledgeable assistant helping Indian consumers understand car insurance. "
    "When asked about car insurance companies or comparisons, provide detailed, balanced, "
    "and factual information about the Indian market. List specific company names wherever relevant."
)


def _get_client():
    """Build and return a Gemini client.  Raises ValueError if key is absent."""
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY environment variable is not set.\n"
            "  Fix: Go to https://aistudio.google.com/app/apikey, sign in with your "
            "Google account, click 'Create API key', and add it as a GitHub Secret "
            "named GEMINI_API_KEY."
        )
    from google import genai
    return genai.Client(api_key=api_key)


def _extract_sources(response) -> list[str]:
    """Pull grounding source URLs from the response metadata (best-effort)."""
    sources: list[str] = []
    try:
        chunks = (
            response.candidates[0]
            .grounding_metadata
            .grounding_chunks
        )
        for chunk in chunks:
            if hasattr(chunk, "web") and chunk.web and chunk.web.uri:
                sources.append(chunk.web.uri)
    except (AttributeError, IndexError, TypeError):
        pass
    return sources[:5]  # cap at 5 sources


def get_google_ai_response(prompt: str) -> str:
    """
    Query Gemini 2.0 Flash with Google Search grounding and return the
    response text.  Appends source URLs when grounding metadata is available.
    Raises on hard API errors so the caller can log and continue.
    """
    from google.genai import types

    client = _get_client()

    response = client.models.generate_content(
        model=_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=_SYSTEM_PROMPT,
            tools=[types.Tool(google_search=types.GoogleSearch())],
            temperature=0.3,
        ),
    )

    text = (response.text or "").strip()
    if not text:
        return "Unexpected response format: Gemini returned an empty response"

    # Append grounding sources so analysts can verify what web content was used
    sources = _extract_sources(response)
    if sources:
        text += "\n\n[Grounding sources: " + ", ".join(sources) + "]"

    return text


def test_connection() -> tuple[bool, str]:
    """
    Lightweight connectivity check — does NOT use Search grounding (saves quota).
    Returns (True, "Connection successful") or (False, plain-English error).
    """
    try:
        client = _get_client()
    except ValueError as e:
        return False, str(e)

    try:
        from google.genai import types
        response = client.models.generate_content(
            model=_MODEL,
            contents="Reply with the single word OK.",
            config=types.GenerateContentConfig(temperature=0.0),
        )
        if response.text:
            return True, "Connection successful"
        return False, "Empty response from Gemini API — unexpected format"

    except Exception as e:
        msg = str(e)
        if "API_KEY_INVALID" in msg or "401" in msg or "invalid" in msg.lower():
            return False, (
                "Invalid API key — your GEMINI_API_KEY is wrong or has been revoked.\n"
                "  Fix: Go to https://aistudio.google.com/app/apikey, delete the old key, "
                "create a new one, and update the GEMINI_API_KEY GitHub Secret."
            )
        if "429" in msg or "RESOURCE_EXHAUSTED" in msg or "quota" in msg.lower():
            return False, (
                "Rate limit or quota exceeded — you have hit the Gemini free tier limit.\n"
                "  The free tier allows 1,500 requests/day. This tracker uses ~8/day, "
                "so this is unexpected. Check usage at https://aistudio.google.com/"
            )
        return False, f"Gemini connection failed: {msg}"
