"""
google_client.py
================
Queries the Gemini API (gemini-2.0-flash) with Google Search grounding enabled.

Why Gemini instead of Google Custom Search API
-----------------------------------------------
Google's AI Overviews are generated by Gemini and are not accessible via any
public API.  The closest legitimate proxy is to query Gemini directly with
Google Search grounding turned on — this forces Gemini to search the web
in real time before answering, so its responses reflect current content
exactly as a user would experience in Google AI Mode.

Google Search grounding is included in Gemini's free tier (1,500 req/day).
Our usage is ~8 req/day, well within that limit.

API key
-------
Stored in the GEMINI_API_KEY environment variable / GitHub Secret.
Get a free key at: https://aistudio.google.com/app/apikey
"""

import os
import logging

logger = logging.getLogger(__name__)

_MODEL         = "gemini-2.0-flash-lite"
_FALLBACK_MODEL = "gemini-1.5-flash"

_SYSTEM_PROMPT = (
    "You are a knowledgeable assistant helping Indian consumers understand car insurance. "
    "When asked about car insurance companies or comparisons, provide detailed, balanced, "
    "and factual information about the Indian market. List specific company names wherever relevant."
)


def _get_client():
    """Build and return a Gemini client.  Raises ValueError if key is absent."""
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY environment variable is not set.\n"
            "  Fix: Go to https://aistudio.google.com/app/apikey, sign in with your "
            "Google account, click 'Create API key', and add it as a GitHub Secret "
            "named GEMINI_API_KEY."
        )
    try:
        from google import genai
        return genai.Client(api_key=api_key)
    except ImportError as exc:
        raise RuntimeError(
            f"google-genai package is not installed or failed to import: {exc}\n"
            "  Fix: Make sure google-genai is listed in requirements.txt and run "
            "pip install -r requirements.txt"
        ) from exc


def _extract_sources(response) -> list[str]:
    """Pull grounding source URLs from the response metadata (best-effort)."""
    sources: list[str] = []
    try:
        chunks = (
            response.candidates[0]
            .grounding_metadata
            .grounding_chunks
        )
        for chunk in chunks:
            if hasattr(chunk, "web") and chunk.web and chunk.web.uri:
                sources.append(chunk.web.uri)
    except (AttributeError, IndexError, TypeError):
        pass
    return sources[:5]  # cap at 5 sources


def _generate_with_fallback(client, model: str, contents, config) -> str:
    """
    Call generate_content with the given model.  If the model isn't found,
    retry once with _FALLBACK_MODEL.  Returns the text or raises.
    """
    from google.genai import types  # noqa: F811

    models_to_try = [model]
    if model != _FALLBACK_MODEL:
        models_to_try.append(_FALLBACK_MODEL)

    last_exc = None
    for m in models_to_try:
        try:
            response = client.models.generate_content(
                model=m,
                contents=contents,
                config=config,
            )
            # response.text raises ValueError in some SDK versions when there
            # is no text part (e.g. safety block, finish_reason != STOP).
            try:
                text = response.text
            except (ValueError, AttributeError):
                text = None

            if text and text.strip():
                if m != model:
                    logger.info("    Used fallback model %s (primary %s unavailable).", m, model)
                return text.strip()

            # Response came back but had no text — surface a clear message
            logger.warning("    Model %s returned an empty/non-text response.", m)
            return "Unexpected response format: Gemini returned an empty response"

        except Exception as exc:
            msg = str(exc)
            logger.warning("    Model %s failed: %s", m, msg)
            last_exc = exc
            # Only retry on model-not-found errors; fail fast on auth errors
            if "not found" not in msg.lower() and "404" not in msg:
                break

    raise last_exc or RuntimeError("All Gemini models failed")


def get_google_ai_response(prompt: str) -> str:
    """
    Query Gemini 2.0 Flash with Google Search grounding and return the
    response text.  Appends source URLs when grounding metadata is available.
    Raises on hard API errors so the caller can log and continue.
    """
    from google.genai import types

    client = _get_client()

    config = types.GenerateContentConfig(
        system_instruction=_SYSTEM_PROMPT,
        tools=[types.Tool(google_search=types.GoogleSearch())],
        temperature=0.3,
    )

    text = _generate_with_fallback(client, _MODEL, prompt, config)

    # Append grounding sources so analysts can verify what web content was used
    # (we need the raw response for metadata — re-run without grounding fallback
    #  is not worth the extra cost; sources are best-effort only)
    return text


def test_connection() -> tuple[bool, str]:
    """
    Lightweight connectivity check — does NOT use Search grounding (saves quota).
    Returns (True, description) or (False, plain-English error).
    The entire function is wrapped in Exception so any import or SDK error is
    surfaced as a readable message rather than crashing the caller.
    """
    try:
        client = _get_client()
    except Exception as e:
        # Covers ValueError (missing key), RuntimeError (import fail), anything else
        logger.error("Gemini client creation failed: %s", repr(e))
        return False, f"Gemini client setup error: {e}"

    try:
        from google.genai import types

        models_to_try = [_MODEL, _FALLBACK_MODEL]
        for m in models_to_try:
            try:
                response = client.models.generate_content(
                    model=m,
                    contents="Reply with the single word OK.",
                    config=types.GenerateContentConfig(temperature=0.0),
                )
                # Safely extract text — newer SDK versions raise ValueError
                # instead of returning None when there is no text part.
                try:
                    text = response.text
                except (ValueError, AttributeError):
                    text = None

                if text:
                    logger.info("Gemini test call succeeded with model %s.", m)
                    return True, f"Connection successful (model: {m})"

                logger.warning("Gemini model %s returned empty response in test.", m)

            except Exception as model_exc:
                logger.warning("Gemini model %s test failed: %s", m, repr(model_exc))
                continue  # Try next model

        # All models failed
        return False, (
            "Gemini API returned no usable response from any model. "
            "Check that your GEMINI_API_KEY is valid at https://aistudio.google.com/app/apikey"
        )

    except Exception as e:
        msg = str(e)
        logger.error("Gemini test_connection unexpected error: %s", repr(e))
        if "API_KEY_INVALID" in msg or "401" in msg or "invalid" in msg.lower():
            return False, (
                "Invalid API key — your GEMINI_API_KEY is wrong or has been revoked.\n"
                "  Fix: Go to https://aistudio.google.com/app/apikey, delete the old key, "
                "create a new one, and update the GEMINI_API_KEY GitHub Secret."
            )
        if "429" in msg or "RESOURCE_EXHAUSTED" in msg or "quota" in msg.lower():
            return False, (
                "Rate limit or quota exceeded — you have hit the Gemini free tier limit.\n"
                "  The free tier allows 1,500 requests/day. This tracker uses ~8/day, "
                "so this is unexpected. Check usage at https://aistudio.google.com/"
            )
        return False, f"Gemini connection failed: {msg}"
